version: '3.8'

services:
  library:
    build: .
    container_name: library
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres@123
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: springbootdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
